name: Deploy Portfolio

on:
  workflow_dispatch:

# IMPORTANT: workflow ko repo write permission dena
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
